"""Defines tools related to syntax and viewing trees."""

from __future__ import annotations
from dataclasses import dataclass
from python_mg._lib_name import SyntacticStructure, MGNode, MGEdge
from PIL import Image
import rustworkx as rx
from rustworkx.visualization import graphviz_draw


def _sort_key(G: rx.PyDiGraph[MGNode, MGEdge], e: int) -> int:
    n, _ = G.get_edge_endpoints_by_index(e)
    return G.get_node_data(n).trace_id()


@dataclass
class Mover:
    """A list of words used to indicate where movement has occurred.

    See :meth:`python_mg.ParseTree.base_string`.
    """

    s: list[str | Mover | Trace]
    """ The moved words """

    trace: int
    """ the trace ID"""


@dataclass
class Trace:
    """A representation of a trace index left by movement."""

    trace: int
    """ the trace ID """


def node_attrs(node: MGNode) -> dict[str, str]:
    """Get the attributes that defines node styling."""
    attrs = {"label": str(node), "ordering": "out"}
    if node.is_stolen():
        attrs["style"] = "dashed"
        attrs["color"] = "gray"
        attrs["fontcolor"] = "gray"

    return attrs


def edge_attrs(edge: MGEdge) -> dict[str, str]:
    """Get the attributes that defines edge styling."""
    if edge.is_move() or edge.is_head_move():
        return {"style": "dashed", "constraint": "false"}
    return {}


class ParseTree:
    """A class for ParseTree generated by :meth:`python_mg.SyntacticStructure.to_tree`.

    It can be used to get a GraphViz representation of the tree or to investigate the
    ParseTree as a graph.
    """

    def __init__(
        self, G: rx.PyDiGraph[MGNode, MGEdge], root: int, structure: SyntacticStructure
    ) -> None:
        """Make a new ParseTree."""
        self.root: int = root
        self.structure: SyntacticStructure = structure

        movement_edges = sorted(
            [x for x in G.filter_edges(lambda x: x.is_move())],
            key=lambda x: _sort_key(G, x),
            reverse=True,
        )
        movements: dict[int, int] = {}

        for e in movement_edges:
            src, tgt = G.get_edge_endpoints_by_index(e)
            trace_id = G.get_node_data(src).trace_id()
            movements[trace_id] = tgt

        self.__movement_sources: dict[int, int] = {m: i for i, m in movements.items()}

        self.G: rx.PyDiGraph[MGNode, MGEdge] = G
        """PyDiGraph[MGNode, MGEdge]: A `RustworkX <https://github.com/Qiskit/rustworkx>`
        _ PyDiGraph which contains the syntactice structure of a sentence"""

    def normal_string(self) -> str:
        """Get the string used by a ParseTree.

        Returns
        -------
        str
            the parsed sentence

        """
        return str(self.structure)

    def base_string(self) -> list[str | Mover | Trace]:
        """Get a richer representation of the parsed string.

        This representation has traces where movement had occurred, and
        :meth:`python_mg.Mover` objects to indicated moved phrases.

        Returns
        -------
        str
            the parsed sentence

        """
        linear_order = self.__explore(self.root)
        return linear_order

    def to_dot(self) -> str | None:
        """Convert a tree to GraphViz DOT format.

        Returns
        -------
        str
            The dot file for this tree

        """
        return self.G.to_dot(node_attr=node_attrs, edge_attr=edge_attrs)

    def to_image(self) -> Image.Image:
        """Convert a tree to a PIL Image.

        Returns
        -------
        Image
            An image representation of the tree

        """
        return graphviz_draw(
            self.G,
            node_attr_fn=node_attrs,
            edge_attr_fn=edge_attrs,
        )

    def __explore(self, n_i: int) -> list[str | Mover | Trace]:
        out: list[str | Mover | Trace] = []
        children = [(str(e), n) for (_, n, e) in self.G.out_edges(n_i)]
        left_children = [n for (e, n) in children if e == "MergeLeft"]
        right_children = [n for (e, n) in children if e == "MergeRight"]
        for child in left_children:
            out += self.__explore(child)

        node = self.G.get_node_data(n_i)
        s = self.G.get_node_data(n_i).lemma_string()
        if node.is_trace():
            out.append(Trace(node.trace_id()))
        elif s != "" and not node.is_stolen():
            out.append(s)

        for child in right_children:
            out += self.__explore(child)

        if n_i in self.__movement_sources:
            return [Mover(out, self.__movement_sources[n_i])]

        return out


def to_tree(self: SyntacticStructure) -> ParseTree:
    """Convert a SyntacticStructure to a ParseTree.

    Returns
    -------
    :meth:`python_mg.ParseTree`
        The SyntacticStructure as a :meth:`python_mg.ParseTree`

    """
    nodes, edges, root = self.__to_tree_inner()  # pyright: ignore[reportPrivateUsage]

    # This will usually be the identity function, but if not, we do this.
    # Waste computation in exchange for not having a horrible headache
    old2new: dict[int, int] = {}

    G = rx.PyDiGraph()
    for old_node_i, node in nodes:
        new_node = G.add_node(node)
        old2new[old_node_i] = new_node

    for old_src, old_tgt, edge in edges:
        _ = G.add_edge(old2new[old_src], old2new[old_tgt], edge)

    return ParseTree(G, old2new[root], self)
