use std::fmt::Display;

use crate::{
    graphing::{PyMgEdge, PyMgNode},
    semantics::PyMeaning,
};

use super::PyLexicon;
use logprob::LogProb;
use minimalist_grammar_parser::{PhonContent, RulePool, lexicon::LexicalEntry};
use pyo3::{exceptions::PyValueError, prelude::*};

#[pyclass(name = "SyntacticStructure", str, eq, frozen)]
#[derive(Debug)]
///The representation of a syntactic structure generated by a grammar, or alternatively the result
///of parsing a string.
pub struct PySyntacticStructure {
    prob: LogProb<f64>,
    string: Vec<PhonContent<String>>,
    rules: RulePool,
    meaning: Option<Vec<PyMeaning>>,
    lex: Py<PyLexicon>,
}

impl PartialEq for PySyntacticStructure {
    fn eq(&self, other: &Self) -> bool {
        self.prob == other.prob && self.string == other.string && self.rules == other.rules
    }
}

impl Display for PySyntacticStructure {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let len = self.string.len();
        for (i, x) in self.string.iter().enumerate() {
            match x {
                PhonContent::Normal(s) => write!(f, "{s}")?,
                PhonContent::Affixed(items) => write!(f, "{}", items.join("-"))?,
            };
            if i != len - 1 {
                write!(f, " ")?;
            }
        }
        Ok(())
    }
}

impl PySyntacticStructure {
    pub fn new(
        lex: Py<PyLexicon>,
        prob: LogProb<f64>,
        string: Vec<PhonContent<String>>,
        rules: RulePool,
    ) -> PySyntacticStructure {
        let py_lex = lex.get();
        PySyntacticStructure {
            prob,
            meaning: py_lex.semantics().map(|lexicon| {
                rules
                    .to_interpretation(lexicon)
                    .map(|(expr, _)| {
                        let s = py_lex.backing_string();
                        unsafe { PyMeaning::from_other(expr, s) }
                    })
                    .collect()
            }),
            rules,
            string,
            lex,
        }
    }

    pub fn into_syntax_structure(
        lexicon: &Bound<'_, PyLexicon>,
        prob: LogProb<f64>,
        string: &[PhonContent<&str>],
        rules: RulePool,
    ) -> PySyntacticStructure {
        let py_lex = lexicon.get();
        PySyntacticStructure {
            prob,
            meaning: py_lex.semantics().map(|lexicon| {
                rules
                    .to_interpretation(lexicon)
                    .map(|(expr, _)| {
                        let s = py_lex.backing_string();
                        unsafe { PyMeaning::from_other(expr, s) }
                    })
                    .collect()
            }),
            rules,
            string: string
                .iter()
                .map(|x| match x {
                    PhonContent::Normal(x) => PhonContent::Normal(x.to_string()),
                    PhonContent::Affixed(items) => {
                        PhonContent::Affixed(items.iter().map(|x| x.to_string()).collect())
                    }
                })
                .collect(),
            lex: lexicon.as_unbound().clone_ref(lexicon.py()),
        }
    }

    pub fn lex(&self) -> &Py<PyLexicon> {
        &self.lex
    }

    pub fn string(&self) -> &Vec<PhonContent<String>> {
        &self.string
    }
}

#[pymethods]
impl PySyntacticStructure {
    ///Returns the interpretation of this SyntacticStructure, provided that its associated Lexicon
    ///has semantics
    ///
    ///Returns
    ///-------
    ///Meaning or none
    ///    The language of thought expression associated with this syntactic structure (if it
    ///    exists)
    #[getter]
    fn meaning(&self) -> Option<Vec<PyMeaning>> {
        self.meaning.clone()
    }

    ///The pronunciation of this SyntacticStructure.
    ///
    ///Returns
    ///-------
    ///list[str]
    ///    A list of strings of each word. Multi-morphemic words are seperated by `-`.
    fn pronunciation(&self) -> Vec<String> {
        self.string
            .iter()
            .map(|x| x.to_string())
            .collect::<Vec<_>>()
    }

    ///The log probability of generating this SyntacticStructure using its associated Lexicon.
    ///
    ///Returns
    ///-------
    ///float
    ///    the log probability
    fn log_prob(&self) -> f64 {
        self.prob.into_inner()
    }

    ///Check whether this string (representing a lexical entry) is used in this tree.
    ///
    ///Returns
    ///-------
    ///bool
    ///    Whether the lexical entry is used
    ///
    ///Raises
    ///------
    ///ValueException
    ///    If the lexical entry is not parseable as a lexical entry.
    fn contains_lexical_entry(&self, s: &str) -> PyResult<bool> {
        let lex = self.lex.get();
        let entry = LexicalEntry::parse(s).map_err(|e| PyValueError::new_err(e.to_string()))?;
        Ok(lex
            .lexeme_to_id
            .get(&entry)
            .is_some_and(|x| self.rules.used_lemmas().any(|y| &y == x)))
    }

    ///The probability of generating this SyntacticStructure using its associated Lexicon.
    ///
    ///Parameters
    ///----------
    ///s : str or None
    ///    The word (or empty word) that may or may not be present
    ///
    ///Returns
    ///-------
    ///bool
    ///    whether the word is present in the structure
    fn contains_word(&self, mut s: Option<&str>) -> bool {
        let lex = self.lex.get();
        if let Some(s_inner) = &s
            && s_inner.is_empty()
        {
            s = None;
        }
        lex.lemma_to_id
            .get(&s.into())
            .is_some_and(|x| self.rules.used_lemmas().any(|y| x.contains(&y)))
    }

    ///The probability of generating this SyntacticStructure using its associated Lexicon.
    ///
    ///Returns
    ///-------
    ///float
    ///    the probability of the structure
    fn prob(&self) -> f64 {
        self.prob.into_inner().exp()
    }

    ///The number of derivational steps necessary to derive this SyntacticStructure using its Lexicon
    ///
    ///Returns
    ///-------
    ///int
    ///    the number of steps
    fn n_steps(&self) -> usize {
        self.rules.n_steps()
    }

    ///Turns the SyntacticStructure into a tree that can be rendered with LaTeX.
    ///Requires including `latex-commands.tex <https://github.com/MichaelGoodale/python-mg/blob/master/latex-commands.tex>`_) in the LaTeX preamble.
    ///
    ///Returns
    ///-------
    ///str
    ///    A LaTeX representation of the parse tree
    fn latex(&self) -> String {
        let lex = self.lex.get();
        lex.lexicon
            .lexicon()
            .derivation(self.rules.clone())
            .tree()
            .latex()
    }

    ///The maximum number of moving elements stored in memory at one time.
    ///
    ///Returns
    ///-------
    ///int
    ///    the maximum number of moved items held in memory in the derivation
    fn max_memory_load(&self) -> usize {
        self.rules.max_memory_load()
    }

    #[allow(clippy::type_complexity)]
    fn __to_tree_inner(&self) -> (Vec<(usize, PyMgNode)>, Vec<(usize, usize, PyMgEdge)>, usize) {
        let d = self
            .lex
            .get()
            .lexicon
            .lexicon()
            .derivation(self.rules.clone());
        let tree = d.tree();
        let (g, root) = tree.petgraph();
        let nodes = g
            .node_indices()
            .map(|n| {
                (
                    n.index(),
                    PyMgNode(
                        g.node_weight(n)
                            .unwrap()
                            .clone()
                            .map(|x| x.to_string(), |x| x.to_string()),
                    ),
                )
            })
            .collect::<Vec<_>>();

        let mut edges = g
            .edge_indices()
            .map(|e| {
                let (src, tgt) = g.edge_endpoints(e).unwrap();
                (
                    src.index(),
                    tgt.index(),
                    PyMgEdge(*g.edge_weight(e).unwrap()),
                )
            })
            .collect::<Vec<_>>();

        edges.sort_by_key(|(_, _, x)| x.0);
        (nodes, edges, root.index())
    }
}
